//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedisImpl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zjzxlh")]
        public string Domain
        {
            get
            {
                return ((string)(this["Domain"]));
            }
            set
            {
                this["Domain"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSCRMAdmin")]
        public string UserName
        {
            get
            {
                return ((string)(this["UserName"]));
            }
            set
            {
                this["UserName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.43/ubgCRM/api/data/v8.0/")]
        public string WebUriDev
        {
            get
            {
                return ((string)(this["WebUriDev"]));
            }
            set
            {
                this["WebUriDev"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.43/XRMServices/2011/Discovery.svc")]
        public string DiscoveryUriDev
        {
            get
            {
                return ((string)(this["DiscoveryUriDev"]));
            }
            set
            {
                this["DiscoveryUriDev"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.43/ubgCRM/XRMServices/2011/Organization.svc")]
        public string OrganizationUriDev
        {
            get
            {
                return ((string)(this["OrganizationUriDev"]));
            }
            set
            {
                this["OrganizationUriDev"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XHHcrm!")]
        public string PassWord
        {
            get
            {
                return ((string)(this["PassWord"]));
            }
            set
            {
                this["PassWord"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.42/ubgCRM/api/data/v8.0/")]
        public string WebUriTest
        {
            get
            {
                return ((string)(this["WebUriTest"]));
            }
            set
            {
                this["WebUriTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.42/XRMServices/2011/Discovery.svc")]
        public string DiscoveryUriTest
        {
            get
            {
                return ((string)(this["DiscoveryUriTest"]));
            }
            set
            {
                this["DiscoveryUriTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.42/ubgCRM/XRMServices/2011/Organization.svc")]
        public string OrganizationUriTest
        {
            get
            {
                return ((string)(this["OrganizationUriTest"]));
            }
            set
            {
                this["OrganizationUriTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xhhtest")]
        public string DomainTest
        {
            get
            {
                return ((string)(this["DomainTest"]));
            }
            set
            {
                this["DomainTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CRMAdmin")]
        public string UserNameTest
        {
            get
            {
                return ((string)(this["UserNameTest"]));
            }
            set
            {
                this["UserNameTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XHHcrm!")]
        public string PassWordTest
        {
            get
            {
                return ((string)(this["PassWordTest"]));
            }
            set
            {
                this["PassWordTest"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.60.7/ubgCRM/XRMServices/2011/Organization.svc")]
        public string OrganizationUriOfficial
        {
            get
            {
                return ((string)(this["OrganizationUriOfficial"]));
            }
            set
            {
                this["OrganizationUriOfficial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.60.7/ubgCRM/api/data/v8.0/")]
        public string WebUriOfficial
        {
            get
            {
                return ((string)(this["WebUriOfficial"]));
            }
            set
            {
                this["WebUriOfficial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.60.7/XRMServices/2011/Discovery.svc")]
        public string DiscoveryUriOfficial
        {
            get
            {
                return ((string)(this["DiscoveryUriOfficial"]));
            }
            set
            {
                this["DiscoveryUriOfficial"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.43")]
        public string Dev1Address
        {
            get
            {
                return ((string)(this["Dev1Address"]));
            }
            set
            {
                this["Dev1Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.42")]
        public string Test1Address
        {
            get
            {
                return ((string)(this["Test1Address"]));
            }
            set
            {
                this["Test1Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.65 ")]
        public string YW1Address
        {
            get
            {
                return ((string)(this["YW1Address"]));
            }
            set
            {
                this["YW1Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.60.7")]
        public string Official1Address
        {
            get
            {
                return ((string)(this["Official1Address"]));
            }
            set
            {
                this["Official1Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.60.8")]
        public string Official2Address
        {
            get
            {
                return ((string)(this["Official2Address"]));
            }
            set
            {
                this["Official2Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.44")]
        public string Dev1SQLAddress
        {
            get
            {
                return ((string)(this["Dev1SQLAddress"]));
            }
            set
            {
                this["Dev1SQLAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.30")]
        public string Dev2SQLAddress
        {
            get
            {
                return ((string)(this["Dev2SQLAddress"]));
            }
            set
            {
                this["Dev2SQLAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.30")]
        public string Dev2Address
        {
            get
            {
                return ((string)(this["Dev2Address"]));
            }
            set
            {
                this["Dev2Address"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.38")]
        public string Test1SQLAddress
        {
            get
            {
                return ((string)(this["Test1SQLAddress"]));
            }
            set
            {
                this["Test1SQLAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.8.65")]
        public string YW1SQLAddress
        {
            get
            {
                return ((string)(this["YW1SQLAddress"]));
            }
            set
            {
                this["YW1SQLAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.50.60.9")]
        public string OfficialSQLAddress
        {
            get
            {
                return ((string)(this["OfficialSQLAddress"]));
            }
            set
            {
                this["OfficialSQLAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crmReader")]
        public string SQLDBReader
        {
            get
            {
                return ((string)(this["SQLDBReader"]));
            }
            set
            {
                this["SQLDBReader"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zjzxlh")]
        public string DomainYW
        {
            get
            {
                return ((string)(this["DomainYW"]));
            }
            set
            {
                this["DomainYW"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mscrmadminyw")]
        public string UserNameYW
        {
            get
            {
                return ((string)(this["UserNameYW"]));
            }
            set
            {
                this["UserNameYW"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XHHcrm!")]
        public string PassWordYW
        {
            get
            {
                return ((string)(this["PassWordYW"]));
            }
            set
            {
                this["PassWordYW"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.65/ubgCRMYW/api/data/v8.0/")]
        public string WebUriYW
        {
            get
            {
                return ((string)(this["WebUriYW"]));
            }
            set
            {
                this["WebUriYW"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.50.8.65/ubgCRMYW/XRMServices/2011/Organization.svc")]
        public string OrganizationUriYW
        {
            get
            {
                return ((string)(this["OrganizationUriYW"]));
            }
            set
            {
                this["OrganizationUriYW"] = value;
            }
        }
    }
}
